name: m183_lb2_node

services:
  db:
    build: ./db
    container_name: m183-lb2-db
    ports:
       - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t

  web:
    image: node:latest
    user: "node"
    working_dir: /home/node/app
    container_name: m183-lb2-web
    environment:
      - DBSERVER=m183-lb2-db
      - NODE_ENV=production
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ../todo-list-node
        target: /home/node/app
    command: "npm start"
